import { formatStringForFile } from '@dlb/scripts/generation/utils';
import { IClassAbility } from '@dlb/types/generation';

export const generateClassAbilityIdEnumFileString = (
	classAbilities: IClassAbility[]
): string => {
	const classAbilityIdEnumsString = classAbilities.map(
		(classAbility) => `${classAbility.id} = '${classAbility.id}',`
	);
	const setDataFileSource = `// This file is generated by the generateModIdEnums.ts script.
	// Do not manually make changes to this file.
  
	export enum EClassAbilityId {
		${classAbilityIdEnumsString.join('\n')}
	}
	`;
	return formatStringForFile(setDataFileSource);
};
