import { formatStringForFile } from '@dlb/scripts/generation/utils';
import { IGrenade } from '@dlb/types/generation';

export const generateGrenadeIdEnumFileString = (
	grenades: IGrenade[]
): string => {
	const grenadeIdEnumsString = grenades.map(
		(grenade) => `${grenade.id} = "${grenade.id}",`
	);
	const setDataFileSource = `// This file is generated by the generateGrenadeIdEnum.ts script.
	// Do not manually make changes to this file.
  
	export enum EGrenadeId {
		${grenadeIdEnumsString.join('\n')}
	}
	`;
	return formatStringForFile(setDataFileSource);
};
