import { formatStringForFile } from '@dlb/scripts/generation/utils';
import { IFragment } from '@dlb/types/generation';

export const generateFragmentIdEnumFileString = (
	fragments: IFragment[]
): string => {
	const fragmentIdEnumsString = fragments.map(
		(fragment) => `${fragment.id} = "${fragment.id}",`
	);
	const setDataFileSource = `// This file is generated by the generateFragmentIdEnum.ts script.
	// Do not manually make changes to this file.
  
	export enum EFragmentId {
		${fragmentIdEnumsString.join('\n')}
	}
	`;
	return formatStringForFile(setDataFileSource);
};
