import { formatStringForFile } from '@dlb/scripts/generation/utils';
import { IAspect } from '@dlb/types/generation';

export const generateAspectIdEnumFileString = (aspects: IAspect[]): string => {
	const aspectIdEnumsString = aspects.map(
		(aspect) => `${aspect.id} = '${aspect.id}',`
	);
	const setDataFileSource = `// This file is generated by the generateModIdEnums.ts script.
	// Do not manually make changes to this file.
  
	export enum EAspectId {
		${aspectIdEnumsString.join('\n')}
	}
	`;
	return formatStringForFile(setDataFileSource);
};
