import { EAspectId } from '@dlb/generated/aspect/EAspectId';
import {
	formatStringForFile,
	getSerializableObject,
} from '@dlb/scripts/generation/utils';
import { IAspect } from '@dlb/types/generation';

export const generateAspectMapping = (aspects: IAspect[]): string => {
	const enumsToSerialize = {
		// armorSlotId: { enumDefinition: EArmorSlotId, enumName: 'EArmorSlotId' },
		id: { enumDefinition: EAspectId, enumName: 'EAspectId' },
		// elementId: { enumDefinition: EElementId, enumName: 'EElementId' },
	};

	const serializeAspects: Record<string, unknown>[] = [];
	aspects.forEach((aspect) => {
		const serializedAspect = { ...aspect } as Record<string, unknown>;
		// TODO: This is dumb. We shouldn't serialize the whole object. Just the key/value pair that we need per iteration
		Object.keys(enumsToSerialize).forEach((key) => {
			const serializedResult = getSerializableObject(
				serializedAspect,
				key,
				enumsToSerialize[key].enumDefinition,
				enumsToSerialize[key].enumName
			) as Record<string, unknown>;
			serializedAspect[key] = serializedResult[key];
		});
		serializeAspects.push(serializedAspect);
	});

	const aspectIdToAspectMappingString = serializeAspects.map(
		(aspect) => `[${aspect.id}]: ${JSON.stringify(aspect, null, 2)},`
	);

	const setDataFileSource = `// This file is generated by the generateAspectMapping.ts script.
	// Do not manually make changes to this file.

	import { EnumDictionary } from '@dlb/types/globals';
	import { IAspect } from '@dlb/types/generation';
  import { EAspectId } from '@dlb/generated/aspect/EAspectId';

	export const AspectIdToAspectMapping: EnumDictionary<EAspectId, IAspect> = {
		${aspectIdToAspectMappingString.join(' ')}
	}
	`;
	return formatStringForFile(setDataFileSource);
};
